name:                shun
version:             0.1.0.0
github:              "josselinauguste/shun"
license:             BSD3
author:              "Josselin Auguste"
maintainer:          "jauguste@iblop.net"
copyright:           "2018 Josselin Auguste"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/josselinauguste/shun#readme>

dependencies:
- base >= 4.7 && < 5
- time
- cryptohash-sha256
- bytestring

library:
  source-dirs: src

executables:
  shun-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shun

tests:
  shun-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shun
    - hspec
